### ISSUE TITLE
“Average Benefit” que sale es muy negativo

### ISSUE THREAD

**Issue by SanPen** [SanPen/DesalinationPlant#4]
@Enrique1985 
El “Average Benefit” que sale es muy negativo (-2, 3, 4 millones al año cuando toda la instalación debiera costar eso, 3 ó 4 millones)

**Comment by SanPen** [comment]
De nuevo, ¿puedes poner un ejemplo de contexto para poder ver si hay un error?

**Comment by Enrique1985** [comment]
Para 300 iteraciones 
Average benefit:	-3,062,564.18 €/year.
LCOE:		2.660179 €/kWh.

**Comment by Enrique1985** [comment]
Cuando selecciono uno que tenga el LCOE de alrededor de 3.5 céntimos (más o menos lo que estoy buscando) sale esto, el coste total negativo

Conditions: 

Amortization years:	25
Discount rate:	0.03
Optimizing for:	0_MIN_LCOE

Results: 

Solar farm size:	1.00/ best:(2,634.00) kW.
Wind farm size:	1,441.73/ best:(1.72) kW.
Storage size:	29.11/ best:(107.26) kWh.

Solar farm cost:	700.00 €.
Wind farm cost:	1,297,554.36 €.
Storage cost:	26,200.73 €.

Total costs:		-805,169.49 €.
Total income:	8,261,707.80 €.
Average benefit:	348,726.05 €/year.
LCOE:		-0.032699 €/kWh.

**Comment by SanPen** [comment]
Hay un error en como se trata el input the porcentaje de mantenimiento

**Comment by SanPen** [comment]
Otro asunto es que el LCOE no es una buena métrica para este problema.
La razón es que se hacen más cosas que exportar electricidad.
Buenas métricas son la maximización del beneficio o la minimización del tiempo de amortización.

El LCOE tiene sentido si sólo vendo electricidad.
